// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCby0PxZcFa5Cf5QjR414o8NANeiP55xSU',
    appId: '1:510408775482:web:093b4400bc313d6731e203',
    messagingSenderId: '510408775482',
    projectId: 'smart-fish-feeder-354b0',
    authDomain: 'smart-fish-feeder-354b0.firebaseapp.com',
    databaseURL:
        'https://smart-fish-feeder-354b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-354b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBY34qfX8tFDLGliIgA0XqRCLJX4qztI',
    appId: '1:510408775482:android:206174d8f3feb68531e203',
    messagingSenderId: '510408775482',
    projectId: 'smart-fish-feeder-354b0',
    databaseURL:
        'https://smart-fish-feeder-354b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-354b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbuD_xhEvmmhpOaqgbz6EdOYMUFeIZT8',
    appId: '1:510408775482:ios:ffb24f50fc6d180031e203',
    messagingSenderId: '510408775482',
    projectId: 'smart-fish-feeder-354b0',
    databaseURL:
        'https://smart-fish-feeder-354b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-354b0.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARbuD_xhEvmmhpOaqgbz6EdOYMUFeIZT8',
    appId: '1:510408775482:ios:ffb24f50fc6d180031e203',
    messagingSenderId: '510408775482',
    projectId: 'smart-fish-feeder-354b0',
    databaseURL:
        'https://smart-fish-feeder-354b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-354b0.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCby0PxZcFa5Cf5QjR414o8NANeiP55xSU',
    appId: '1:510408775482:web:06f77a8425550d5231e203',
    messagingSenderId: '510408775482',
    projectId: 'smart-fish-feeder-354b0',
    authDomain: 'smart-fish-feeder-354b0.firebaseapp.com',
    databaseURL:
        'https://smart-fish-feeder-354b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fish-feeder-354b0.firebasestorage.app',
  );
}
